config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'tasks', to: 'tasks#index'
  # post 'tasks', to: 'tasks#create'
  # get 'tasks/new', to: 'tasks#new', as: :new_task
  # get 'tasks/:id', to: 'tasks#show', as: :task
  # get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  # patch 'tasks/:id', to: 'tasks#update'
  # delete 'tasks/:id', to: 'tasks#destroy'

  root to: "pages#home"
  
  resources :products
  resources :suppliers, only: [:index, :show, :new, :create]
  
  resources :projects do
    resources :suppliers do
      resources :tasks
    end

    resources :work_progresses, only: [:new, :create, :edit, :update]

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :work_progresses
	has_many :suppliers, through: :work_progresses
	has_many :tasks
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :work_progresses
  has_many :projects, through: :work_progresses
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :projects
  belongs_to :suppliers
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/work_progress.rb
class WorkProgress < ApplicationRecord
  belongs_to :project
  belongs_to :supplier
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@dufrio = Dufrio::V1::DufrioRepository.call
		@climario = Climario::V1::ClimarioRepository.call
		@poloar = Poloar::V1::PoloarRepository.call
		if params[:query].present?
     		@dufrio = @dufrio.select { |key| key.to_s.include? params[:query].capitalize }
			@climario = @climario.select { |key| key.to_s.include? params[:query].capitalize }
			@poloar = @poloar.select { |key| key.to_s.include? params[:query].capitalize }
    end
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
    @suppliers = Supplier.all
  end

  def show
    @project = Project.find(params[:id])
  end

end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
	def index
		@suppliers = Supplier.all
	end

	def show
		@supplier = Supplier.find(params[:id])
	end

	def new
		#@project = Project.find(params[:project_id])
		@supplier = Supplier.new
	end

	def create
		@supplier = Supplier.new(supplier_params)
		#project = Project.find(params[:project_id])
		#@supplier.project_id = project.id
		@supplier.save

		redirect_to suppliers_path
	end

	private

	def supplier_params
		params.require(:supplier).permit(:name, :category)
	end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :home

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    project = Project.find(params[:task][:projects_id])
    task = Task.new(task_params)
    task.projects_id = project.id
  
    if task.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to tasks_path, notice: "Task criada." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :completed, :photo, :projects_id)
  end
end

app/controllers/work_progresses_controller.rb
class WorkProgressesController < ApplicationController
  def new
    @project = Project.find(params[:project_id])
    @supplier = Supplier.find(params[:supplier][:supplier_id])
    @work_progress = WorkProgress.new
  end

  def create 
    @work_progress = WorkProgress.new(work_progress_params)
		project = Project.find(params[:project_id])
    supplier = Supplier.find(params[:work_progress][:supplier])
		@work_progress.project_id = project.id
    @work_progress.supplier_id = supplier.id
		@work_progress.save

		redirect_to projects_path
  end

  def edit
    @work_progress = WorkProgress.find(params[:id])
  end

  def update
    @work_progress = WorkProgress.find(params[:id])
    @work_progress.update(work_progress_params)

    redirect_to project_path(@work_progress.project.id)
  end

  private

	def work_progress_params
		params.require(:work_progress).permit(:total)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/work_progress_helper.rb
module WorkProgressHelper
end

app/helpers/work_progresses_helper.rb
module WorkProgressesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<%= form_with url: products_path, method: :get, data: { turbo_frame: "results", controller: "form", action: "input->form#submit"} do |f| %>
	<%= f.label :nome %>
	<%= f.text_field :query, value: params[:query] %>
	<%= f.submit "Find" %>
<% end %>

<%= turbo_frame_tag id="results" do %>
	<div>
		<h1>Dufrio</h1>
			<%  @dufrio.each do |product| %>
				<div>
					<%= product[0] %>
					<%= product[1] %>
				</div>
			<% end %>
	</div>

	<div>
		<h1>Climario</h1>
			<%  @climario.each do |product| %>
				<div>
					<%= product[0] %>
					<%= product[1] %>
				</div>
			<% end %>
	</div>

	<div>
		<h1>Poloar</h1>
			<%  @poloar.each do |product| %>
				<div>
					<%= product[0] %>
					<%= product[1] %>
				</div>
			<% end %>
	</div>
<% end %>

app/views/projects/index.html.erb
<div class="projects">
	<% @projects.each do |project| %>
		<h4><i class="fa-solid fa-helmet-safety fa-beat-fade" style="color: #7fa9f0;"></i><%= link_to project.name, project_path(project) %></h4>
	<% end %>
</div>

app/views/projects/show.html.erb
<div class="projects">
	<%= @project.name %>

	<h4>Fornecedores</h4>
	<h3>Adicionar fornecedor</h4>

	<%= form_tag(new_project_work_progress_path(params[:id]), method: "get") do %>
		<%= select("supplier", "supplier_id", Supplier.all.collect {|p| [ p.name, p.id ] }) %>
		<%= submit_tag("adicionar") %>
	<% end %>

		<div class="supplier-progress">
			<div class="list">
				<%  @project.suppliers.each do |supplier| %>
					<h1><%= supplier.name %></h1>
				<% end %>
			</div>

	
				<div class="list">
					<% @project.work_progresses.each do |work| %>
						<%= turbo_frame_tag id="edit-supplier" do %>	
							<h1><%= work.total %>%<%= link_to "editar", edit_project_work_progress_path(:project_id => work.project_id, :id => work.id) %></h1>
						<% end %>
					<% end %>
				</div>
		</div>


</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag('logo.png', size: "200x100") %>
    <% end %>


    <ul class="navbar-nav me-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Início", root_path , class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Gerenciador de Tarefas", tasks_path , class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Produtos", products_path , class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Obras", projects_path , class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Fornecedores", suppliers_path , class: "nav-link" %>
        </li>
          <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :get}, class: "nav-link" %>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/suppliers/index.html.erb
<%  @suppliers.each do |sup|%>
  <%= link_to sup.name, supplier_path(sup) %>
<% end %>

app/views/suppliers/new.html.erb
<%= form_with model: @supplier do |f| %>
  <%= f.label :nome %>
  <%= f.text_field :name %>
  <%= f.label :categoria %>
  <%= f.text_field :category %>
  <%= f.submit %> 
<% end %>

app/views/tasks/_form.html.erb
<%= simple_form_for(task) do |f| %>
  <% unless current_user.id > 1 %>
    <div class="form-group"> 
      <%= f.input :title, label: 'Título' %>
    </div>

    <div class="form-group"> 
      <%= f.input :projects_id, collection: Project.all, label: 'Obra' %>
    </div>

    <div class="form-group">
      <%= f.input :description, label: 'Descrição' %>
    </div>
  <% end %>
    <%= f.input :photo, as: :file, label: 'Foto' %>
    
  <% unless f.object.new_record? %>
    <div class="checkbox">
      <label>
        <%= f.check_box :completed %> Realizada
      </label>
    </div>
  <% end %>
  <%= f.button :submit, class: 'btn btn-primary mt-3' %>
<% end %>

app/views/tasks/_tasks.html.erb
<%= turbo_frame_tag id="tasks" do%>
    <div id="tasks">
        <% @tasks.each do |task| %>
            <div>
            <%= image_tag('logo.png', size: '50x50') %>
            <strong><%= link_to task.title, task_path(task.id), class: "tasks-list", data: { turbo_frame: "_top" } %></strong>
            <% if task.completed? %>
                <i class="fa-solid fa-square-check fa-beat-fade" style="color: #4772bd;"></i>
            <% else %>
                <i class="fa-regular fa-square fa-bounce"></i>
            <% end %>
            <%= link_to task_path(task.id), data: {turbo_method: :delete, turbo_confirm: "Delete #{task.title}?"} do %>
                <i class="fa-regular fa-trash-can"></i>
            <% end %>
            </div>
        <% end %>
    </div>
<% end %>

app/views/tasks/create.turbo_stream.erb
<%= turbo_stream.replace "tasks", partial: "tasks/tasks", locals: { tasks: @tasks }%>

app/views/tasks/edit.html.erb
  <div class="container mt-5">
    <h1>Editar tarefa</h1>

    <%= render "form", task: @task %>
  </div>

app/views/tasks/index.html.erb
<div class="container mt-5">
  <h1>Tarefas</h1>
  
  <div id="tasks">
    <%= render "tasks/tasks" %>
  </div>

  <hr>
  <%= turbo_frame_tag id="nova" do %>
    <%= link_to new_task_path do %>
      <i class="fa-solid fa-plus fa-bounce" style="color: #217BA8;"></i> Nova tarefa
    <% end %>
  <% end %>
</div>

app/views/tasks/new.html.erb
<%= turbo_frame_tag id="nova" do %>
  <div class="container mt-5">
    <h1>Nova tarefa</h1>

    <%= render "form", task: @task %>
    <%= link_to tasks_path do %>
      <i class="fa-solid fa-arrow-rotate-left fa-beat"></i>
    <% end %>
  </div>
<% end %>

app/views/tasks/show.html.erb
<div class="container mt-5">
  <div class="d-flex justify-content-start align-items-center mb-4">
    <h1><%= @task.title %></h1>
  </div>

  <p class="well">Descrição: <%= @task.details %></p>
  <% if @task.photo.attached? %>
    <%= cl_image_tag @task.photo.key, height: 300, width: 400, crop: :fill %>
  <% end %>

  <hr>

  <%= link_to edit_task_path(@task.id) do %>
    <i class="fa-solid fa-pencil fa-beat"></i>
  <% end %>
  
  <%= link_to tasks_path do %>
    <i class="fa-solid fa-arrow-rotate-left fa-beat"></i>
  <% end %>
</div>

app/views/work_progresses/edit.html.erb
<%= turbo_frame_tag id="edit-supplier" do %>
  <%= form_with(model:[ :project, @work_progress]) do |f| %>
    <%= f.text_field :total %>
    <%= f.submit "Atualizar" %>
  <% end %>
<% end %>

app/views/work_progresses/new.html.erb
<%= form_with(model:[ :project, @work_progress]) do |f| %>
  <%= f.hidden_field :supplier, value: params[:supplier][:supplier_id] %>
  <%= f.hidden_field :total, value: 0 %>
  <%= f.submit "Confirmar" %>
<% end %>

app/views/work_progresses/update.turbo_stream.erb
<%= turbo_stream.replace "edit-supplier", partial: "tasks/tasks", locals: { tasks: @tasks }%>